name: flutter_samples
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  provider: ^6.1.5
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  flutter_icons: ^1.1.0
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  flutter_sound_lite: ^9.2.13
  flutter_shapes: ^0.3.1
  bezier_chart: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/brayan.jpg
    - assets/images/instagram_redesign/
    - assets/images/nike_shoes/
    - assets/images/smart_parking/
    - assets/images/space_concept/
    - assets/images/diet_fast/
    - assets/images/supercines/
    - assets/images/find_home/
    - assets/images/music_app/
    - assets/images/ecommerce/
    - assets/images/radio_app/
    - assets/images/salud/
    - assets/linkedin/icons/
    - assets/linkedin/images/
    - assets/linkedin/images/users/
    - assets/linkedin/images/posts/

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Black.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
        - asset: assets/fonts/Orbitron-ExtraBold.ttf
        - asset: assets/fonts/Orbitron-Medium.ttf
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-SemiBold.ttf
    - family: Uniwars
      fonts:
        - asset: assets/fonts/Uniwars-Regular.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir.otf
    - family: SFDisplay
      fonts:
        - asset: assets/fonts/sf_display.ttf
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/Aeonik-Black.ttf
          weight: 900
        - asset: assets/fonts/aeonik/Aeonik-Bold.ttf
          weight: 800
        - asset: assets/fonts/aeonik/Aeonik-Medium.ttf
          weight: 600
        - asset: assets/fonts/aeonik/Aeonik-Regular.ttf
          weight: 400
